# Generated by Django 3.2.6 on 2024-07-25 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20240722_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individual_id', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(default='available', max_length=20)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
            ],
        ),
    ]
